//> using publish.name "spaeti"
//> using publish.organization "eu.joaocosta"
//> using publish.url "https://github.com/JD557/spaeti"
//> using publish.vcs "github:JD557/spaeti"
//> using publish.license "MIT"
//> using publish.developer "JD557|João Costa|https://github.com/jd557"
//> using publish.repository "central"
//> using publish.computeVersion "git:tag"
//> using publish.ci.repository "central"
//> using publish.ci.user "env:PUBLISH_USER"
//> using publish.ci.password "env:PUBLISH_PASSWORD"
//> using publish.ci.secretKey "env:PUBLISH_SECRET_KEY"
//> using publish.ci.secretKeyPassword "env:PUBLISH_SECRET_KEY_PASSWORD"
//> using publish.ci.publicKey "env:PUBLISH_PUBLIC_KEY"
